'
' File generated by HDevelop for HALCON/.NET (Visual Basic .NET) Version 20.05.0.0
' Non-ASCII strings in this file are encoded in local-8-bit encoding (cp1252).
'
' Please note that non-ASCII characters in string constants are exported
' as octal codes in order to guarantee that the strings are correctly
' created on all systems, independent on any compiler settings.
'
' Source files with different encoding should not be mixed in one project.
'

Option Strict Off

Option Explicit On

Imports HalconDotNet

Imports System
Imports Microsoft.VisualBasic

Module HDevelopExportUnnamed

    ' Procedures
    ' Local procedures
    Public Sub ForceException()

        ' Initialize local and output iconic variables

        Dim hv_Tuple As HTuple
        ' Initialize local and output control variables
        hv_Tuple = New HTuple()
        Try
            hv_Tuple.Dispose()
            HOperatorSet.ReadTuple(New HTuple("this_file_doesnt_exist.tup"), hv_Tuple)
            ' catch (Exception)
        Catch HDevExpDefaultException1 As HalconException
            Dim MyProcedureName As String
            MyProcedureName = Reflection.MethodBase.GetCurrentMethod().ToString()
            Console.WriteLine("Exception Occured: " + HDevExpDefaultException1.GetErrorMessage + " in procedure " + MyProcedureName.ToString())
            Console.WriteLine("Press any key to continue.")
            Console.ReadKey()

            Throw New ArgumentException("Exception Occured: " + HDevExpDefaultException1.GetErrorMessage + " in procedure " + MyProcedureName.ToString())
        End Try

        Exit Sub
    End Sub

#If Not NO_EXPORT_MAIN Then

    ' Main procedure
    Private Sub action()

        ' Local control variables

        ' Initialize local and output iconic variables

        ' Initialize local and output control variables
        Try
            ForceException()
        Catch MyException As ArgumentException
            Console.WriteLine("Exception occured in " + MyException.TargetSite.ToString)
            Console.WriteLine("Press any key to continue.")
            Console.ReadKey()
            Throw MyException
        End Try

    End Sub

#If Not NO_EXPORT_APP_MAIN Then

    Sub InitHalcon()
        ' Default settings used in HDevelop
        Call HOperatorSet.SetSystem(New HTuple("width"), New HTuple(512))
        Call HOperatorSet.SetSystem(New HTuple("height"), New HTuple(512))
        If (HalconAPI.isWindows) Then
            Call HOperatorSet.SetSystem("use_window_thread", "true")
        End If
    End Sub

    Sub Main(ByVal args() As String)
        Call InitHalcon()
        Try
            Call action()
        Catch HDevExpDefaultException As ArgumentException
            Console.WriteLine(HDevExpDefaultException.Message)
            Console.WriteLine(HDevExpDefaultException.TargetSite.ToString)
            Console.WriteLine("Press any key to close.")
            Console.ReadKey()

        End Try

    End Sub

#End If

#End If

End Module